In [3]:
import numpy as np 
training_sample = 100000
DIGIT = 4

In [4]:
i2w = [str(i) for i in range(10)]+['+']
w2i = {str(v):k for k,v in enumerate(i2w)}

In [5]:
X,Y = [],[]
for i in range(training_sample):
    a = np.random.randint(1001,10000-1)
    b = np.random.randint(1001,10000-1)
    c = str(a+b)
    x = str(a)+'+'+str(b)
    x = '0'*(2*DIGIT+1-len(x)) + x
    c = '0'*(DIGIT+1-len(c)) + c
    
    x = [w2i[i] for i in x]
    c = [w2i[i] for i in c]
    X.append(x)
    Y.append(c)  

In [6]:
import tensorflow  as tf
import tensorflow.keras as keras
from tensorflow.keras import layers,Model

In [7]:
X = np.array(X)
Y = np.array(Y)

In [8]:
X[0]

array([ 5,  1,  7,  9, 10,  3,  7,  4,  8])

In [9]:
i2w

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '+']

In [10]:
Input = layers.Input(shape=(2*DIGIT+1,))

embedding = layers.Embedding(11,32)(Input)
lstm1 = layers.LSTM(64,return_sequences=True,activation='tanh')(embedding)
lstm2 = layers.LSTM(64,return_sequences=False,activation='tanh')(lstm1)

lstm = layers.RepeatVector(DIGIT + 1)(lstm2)

ffn = layers.Dense(128,activation='relu')(lstm)

ffn = layers.Dense(11,activation='sigmoid')(ffn)


model = Model(Input, ffn)

model.compile(optimizer='nadam', loss="sparse_categorical_crossentropy", metrics=["sparse_categorical_accuracy"])
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 9)]               0         
_________________________________________________________________
embedding (Embedding)        (None, 9, 32)             352       
_________________________________________________________________
lstm (LSTM)                  (None, 9, 64)             24832     
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                33024     
_________________________________________________________________
repeat_vector (RepeatVector) (None, 5, 64)             0         
_________________________________________________________________
dense (Dense)                (None, 5, 128)            8320      
_________________________________________________________________
dense_1 (Dense)              (None, 5, 11)            

In [11]:
model.fit(X[:-10000],Y[:-10000],batch_size = 64, epochs = 10,validation_split=.2)

Epoch 1/10
1125/1125 [==============================] - 10s 8ms/step - loss: 2.1891 - sparse_categorical_accuracy: 0.2290 - val_loss: 2.1037 - val_sparse_categorical_accuracy: 0.2801
Epoch 2/10
1125/1125 [==============================] - 9s 8ms/step - loss: 2.0796 - sparse_categorical_accuracy: 0.2809 - val_loss: 2.0634 - val_sparse_categorical_accuracy: 0.2806
Epoch 3/10
1125/1125 [==============================] - 9s 8ms/step - loss: 2.0556 - sparse_categorical_accuracy: 0.2835 - val_loss: 2.0514 - val_sparse_categorical_accuracy: 0.2859
Epoch 4/10
1125/1125 [==============================] - 9s 8ms/step - loss: 2.0448 - sparse_categorical_accuracy: 0.2862 - val_loss: 2.0395 - val_sparse_categorical_accuracy: 0.2872
Epoch 5/10
1125/1125 [==============================] - 10s 9ms/step - loss: 2.0314 - sparse_categorical_accuracy: 0.2885 - val_loss: 2.0282 - val_sparse_categorical_accuracy: 0.2900
Epoch 6/10
1125/1125 [==============================] - 10s 9ms/step - loss: 2.0209 - sp

In [12]:
z = (model.predict(X[-10000:]))

In [13]:
z = z.argmax(axis=-1)

In [ ]:
Y.shape

In [ ]:
z.shape

In [16]:
np.sum(z==Y[-10000:],axis=-1)

array([1, 1, 1, ..., 2, 2, 1])

In [17]:
z

array([[5, 5, 5, 5, 5],
       [1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3],
       ...,
       [1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int64)

In [ ]:
a = layers.Input(shape=(DIGIT,))
b = layers.Input(shape=(DIGIT,))

embedding = layers.Embedding(2*DIGIT+1,32)(layers.con)
lstm1 = layers.LSTM(64,return_sequences=True,activation='tanh')(embedding)
lstm2 = layers.LSTM(64,return_sequences=False,activation='tanh')(lstm1)

lstm = layers.RepeatVector(DIGIT + 1)(lstm2)

ffn = layers.Dense(128,activation='relu')(lstm)

ffn = layers.Dense(11,activation='sigmoid')(ffn)


model = Model(Input, ffn)

model.compile(optimizer='nadam', loss="sparse_categorical_crossentropy", metrics=["sparse_categorical_accuracy"])
model.summary()

In [ ]:
np.random.randint(1000,10000)